### ISSUE TITLE
Why is the TLS docker daemon being removed?

### ISSUE THREAD

**Issue by kuboraam** [trajano/terraform-docker-swarm-aws#18]
Hi, i'd like to understand why you mention in the README that "Docker TLS daemon support will be removed in a future releases. Use https://github.com/docker/cli/pull/1014." ? 

From a "best practice" perspective in production, is ssh better for security reasons? 
According to [this article](https://docs.docker.com/engine/security/protect-access/), they say both are supported.

**Comment by trajano** [comment]
Terraforming with TLS is a bit complicated and so it managing the certificates.  However, I am not sure if I had removed it yet or not, but I know I haven't been keeping it up to date and will likely end with bit rot if it hasn't already.

**Comment by trajano** [comment]
The TLS docker is removed per https://github.com/trajano/terraform-docker-swarm-aws/pull/20
